### ISSUE TITLE
Binary file for arm64 is missing

### ISSUE THREAD

**Issue by dimon222** [Magisk-Modules-Repo/dnscrypt-proxy#36]
Receiving next from magisk when trying to install new version:
```
Creating binary path
Creating config path
Binary file for arm64 is missing!
! Installation failed
```

Magisk 19
Device LYA-L29
Previous version is working without issues.

PS: same issue with regular ARM, build is probably broken

**Comment by tyblib** [comment]
Yes, i have same problem. I just flashed the older ver (2.7.0) and its works fine.

**Comment by WhiCCX0** [comment]
Me too🤣

**Comment by pundoo** [comment]
Same!
Moreover, can't even flash the zip manually. It says 'This zip is not a Magisk Module!'

**Comment by lupzy** [comment]
How to re-zip w/o sub-folder @pundoo

**Comment by jancm** [comment]
install.sh has a few errors in it. Line 160 should be:

unzip -o "$ZIPFILE" 'config/*' 'binary/*' 'common/*' -d $TMPDIR 2>/dev/null

(ZIPFILE instead of ZIP and, because of line 192, you need to also extract common/*)

Also, since you unconditionally changed to bin from xbin (which I think is fine) you also need to change line 204 and setperm on bin instead of xbin.

That will fix all the errors.
